"use client";

import { useEffect, useMemo, useState } from "react";

type Variant = { label: string; price: string; imageIndex?: number };
type CartItem = { productId: string; variantIndex: number; quantity: number };
type ProductImage = { thumb: string; large: string };
type Product = { id: string; name: string; line: string; category: "Touch" | "Sensores" | "Display" | "Decorativos"; summary: string; images: ProductImage[]; imageAlts: string[]; variants: Variant[]; features: string[]; specs: [string, string][]; badge?: string };

const BASE_URL = import.meta.env.BASE_URL;
const IMAGE_BASE = `${BASE_URL}images/products`;
const image = (name: string): ProductImage => ({ thumb: `${IMAGE_BASE}/${name}-thumb.webp`, large: `${IMAGE_BASE}/${name}-large.webp` });
const PRODUCTS: Product[] = [
  { id: "aura", name: "Aura Touch", line: "Esencial", category: "Touch", summary: "El redondo que mejor rota: luz regulable, tres tonos y memoria.", images: [image("aura-1"), image("aura-2"), image("aura-3")], imageAlts: ["Aura Touch redondo con luz", "Aura Touch en ambiente", "Aura Touch completo"], variants: [{ label: "Ø 60 cm", price: "$80.000" }, { label: "Ø 70 cm", price: "$95.000" }, { label: "Ø 80 cm", price: "$100.000" }], features: ["Touch frontal", "Luz fría, cálida y neutra", "Dimmer y memoria"], specs: [["Vidrio", "3 mm"], ["Terminación", "Borde pulido"], ["Instalación", "Kit incluido"]], badge: "Más elegido" },
  { id: "eclipse", name: "Eclipse Display", line: "Tecnología", category: "Display", summary: "Información útil integrada al espejo, sin perder una estética limpia.", images: [image("eclipse-1"), image("eclipse-2"), image("eclipse-3"), image("eclipse-4"), image("eclipse-5")], imageAlts: ["Eclipse Display redondo", "Eclipse Display en ambiente", "Eclipse Display con luz cálida", "Eclipse Display encendido", "Eclipse Display completo"], variants: [{ label: "Ø 60 cm", price: "$105.000" }], features: ["Hora, fecha y temperatura", "Display integrado", "Luz LED perimetral"], specs: [["Vidrio", "3 mm"], ["Terminación", "Borde pulido"], ["Forma", "Redonda"]] },
  { id: "nova", name: "Nova Smart", line: "Premium", category: "Display", summary: "La experiencia completa: pantalla, conectividad, audio y desempañador.", images: [image("nova-1"), image("nova-2"), image("nova-3"), image("nova-4"), image("nova-5")], imageAlts: ["Nova Smart rectangular completo", "Nova Smart en baño moderno", "Nova Smart vertical", "Nova Smart con pantalla", "Nova Smart en ambiente"], variants: [{ label: "90 × 60 cm", price: "$230.000" }], features: ["Pantalla inteligente", "Control Tuya Smart", "Bluetooth y parlantes", "Desempañador"], specs: [["Orientación", "Horizontal o vertical"], ["Conectividad", "Wi-Fi + Bluetooth"], ["Control", "App Tuya Smart"]], badge: "Alta rentabilidad" },
  { id: "colgante", name: "Nórdico Colgante", line: "Deco", category: "Decorativos", summary: "Un diseño atemporal para dormitorios, recibidores y baños secos.", images: [image("colgante-1"), image("colgante-2"), image("colgante-3")], imageAlts: ["Espejo redondo colgante", "Detalle del espejo colgante", "Espejo colgante de cuerpo completo"], variants: [{ label: "50 / 60 cm", price: "Consultar" }], features: ["Correa de P.U.", "Marco símil hierro", "Pin de soporte incluido"], specs: [["Estilo", "Nórdico"], ["Forma", "Redonda"], ["Instalación", "Kit incluido"]] },
  { id: "halo", name: "Halo Gestual", line: "Sensor", category: "Sensores", summary: "Se controla sin tocarlo: ideal para una experiencia más higiénica.", images: [image("halo-1"), image("halo-2"), image("halo-3")], imageAlts: ["Halo Gestual redondo", "Halo Gestual en tocador", "Halo Gestual completo"], variants: [{ label: "Ø 60 cm", price: "$105.000" }], features: ["Encendido sin contacto", "Tres tonos de luz", "Intensidad regulable"], specs: [["Vidrio", "3 mm"], ["Terminación", "Borde pulido"], ["Sensor", "Gestual"]] },
  { id: "lumen", name: "Lumen Sensor", line: "Sensor", category: "Sensores", summary: "La luz responde al acercarte y se apaga automáticamente al retirarte.", images: [image("lumen-1"), image("lumen-2"), image("lumen-3"), image("lumen-4"), image("lumen-5"), image("lumen-6"), image("lumen-7")], imageAlts: ["Lumen rectangular con sensor de presencia", "Lumen rectangular en ambiente", "Lumen rectangular completo", "Lumen redondo con sensor de presencia", "Lumen redondo en tocador", "Lumen redondo encendido", "Lumen redondo completo"], variants: [{ label: "Rect. 70 × 50", price: "$105.000", imageIndex: 0 }, { label: "Redondo 60", price: "$105.000", imageIndex: 3 }, { label: "Redondo 70", price: "$115.000", imageIndex: 3 }], features: ["Sensor de presencia", "Encendido automático", "Apagado a los 20–30 s", "Versión gestual disponible"], specs: [["Vidrio", "3 mm"], ["Terminación", "Borde pulido"], ["Gestual 70 × 50", "$105.000"]] },
  { id: "capsula", name: "Cápsula Display", line: "Diseño", category: "Display", summary: "Silueta orgánica, display integrado y dos terminaciones para elegir.", images: [image("capsula-1"), image("capsula-2"), image("capsula-3"), image("capsula-4")], imageAlts: ["Cápsula Display con marco negro", "Cápsula Display marco negro en ambiente", "Cápsula Display con borde pulido", "Cápsula Display marco pulido en ambiente"], variants: [{ label: "Marco negro", price: "$105.000", imageIndex: 0 }, { label: "Borde pulido", price: "$105.000", imageIndex: 2 }], features: ["Display integrado", "Formato píldora", "Luz LED posterior", "Desempañador"], specs: [["Medida", "70 × 50 cm"], ["Vidrio", "3 mm"], ["Forma", "Píldora / ovalada"]] },
  { id: "arco", name: "Arco Touch", line: "Diseño", category: "Touch", summary: "Espejo decorativo y funcional con tecnología touch, ideal para sumar luz y presencia en baños, dormitorios, recibidores, vestidores y maquilladores.", images: [image("arco-1")], imageAlts: ["Espejo Arco Touch de medio punto"], variants: [{ label: "70 × 50 cm", price: "$85.000", imageIndex: 0 }], features: ["Botón touch", "Tres tonos de luz", "Dimmer integrado"], specs: [["Vidrio", "3 mm"], ["Forma", "Medio punto / romana"], ["Terminación", "Borde pulido"]] },
  { id: "gota", name: "Gota", line: "Diseño", category: "Sensores", summary: "Una forma orgánica con tres alternativas de encendido.", images: [image("gota-1"), image("gota-2"), image("gota-3")], imageAlts: ["Espejo Gota con touch", "Espejo Gota con sensor gestual", "Espejo Gota con sensor de presencia"], variants: [{ label: "Touch", price: "$85.000", imageIndex: 0 }, { label: "Sensor gestual", price: "$98.000", imageIndex: 1 }, { label: "Sensor de presencia", price: "$98.000", imageIndex: 2 }], features: ["Touch o sensor", "Luz LED posterior", "Diseño orgánico"], specs: [["Medida", "70 × 50 cm"], ["Vidrio", "3 mm"], ["Forma", "Gota"]] },
];

const FILTERS = ["Todos", "Touch", "Sensores", "Display", "Decorativos"] as const;
const whatsappNumber = "5493863536486";
const whatsappUrl = (message: string) => `https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`;
const numericPrice = (price: string) => { const value = Number(price.replace(/[^0-9]/g, "")); return Number.isFinite(value) && value > 0 ? value : null; };
const formatPrice = (value: number) => new Intl.NumberFormat("es-AR", { style: "currency", currency: "ARS", maximumFractionDigits: 0 }).format(value);
const variantImageIndex = (product: Product, variantIndex: number) => typeof product.variants[variantIndex]?.imageIndex === "number" && product.images[product.variants[variantIndex].imageIndex!] ? product.variants[variantIndex].imageIndex! : 0;
const generalWhatsappUrl = whatsappUrl("Hola DianubyHome, quiero recibir información sobre el catálogo mayorista de espejos.");
function ArrowIcon() { return <span aria-hidden="true" className="arrow">↗</span>; }
function BrandLockup({ footer = false }: { footer?: boolean }) { return <span className={`brand-lockup${footer ? " footer-brand" : ""}`}><span className="brand-mark"><img src={`${BASE_URL}logo-dianuby.png`} alt="" width="180" height="215" /></span><span className="brand-name">DIANUBY<strong>HOME</strong><small>SMART LIVING</small></span></span>; }

export default function Home() {
  const [filter, setFilter] = useState<(typeof FILTERS)[number]>("Todos");
  const [selected, setSelected] = useState<Product | null>(null);
  const [imageIndex, setImageIndex] = useState(0);
  const [selectedVariant, setSelectedVariant] = useState(0);
  const [modalQuantity, setModalQuantity] = useState(1);
  const [cart, setCart] = useState<CartItem[]>([]);
  const [cartOpen, setCartOpen] = useState(false);
  const [cartReady, setCartReady] = useState(false);
  const filtered = useMemo(() => filter === "Todos" ? PRODUCTS : PRODUCTS.filter((product) => product.category === filter), [filter]);

  useEffect(() => {
    const timer = window.setTimeout(() => {
      try {
        const saved = window.localStorage.getItem("dianuby-cart");
        if (saved) setCart(JSON.parse(saved));
      } catch {
        window.localStorage.removeItem("dianuby-cart");
      }
      setCartReady(true);
    }, 0);
    return () => window.clearTimeout(timer);
  }, []);
  useEffect(() => { if (cartReady) window.localStorage.setItem("dianuby-cart", JSON.stringify(cart)); }, [cart, cartReady]);
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key !== "Escape") return; if (selected) setSelected(null); else setCartOpen(false); }; document.addEventListener("keydown", close); document.body.style.overflow = selected || cartOpen ? "hidden" : ""; return () => { document.removeEventListener("keydown", close); document.body.style.overflow = ""; }; }, [selected, cartOpen]);

  const cartDetails = useMemo(() => cart.flatMap((item) => { const product = PRODUCTS.find((candidate) => candidate.id === item.productId); const variant = product?.variants[item.variantIndex]; return product && variant ? [{ ...item, product, variant }] : []; }), [cart]);
  const totalUnits = cartDetails.reduce((sum, item) => sum + item.quantity, 0);
  const totalPrice = cartDetails.reduce((sum, item) => { const price = numericPrice(item.variant.price); return sum + (price ? price * item.quantity : 0); }, 0);
  const hasPriceToConfirm = cartDetails.some((item) => numericPrice(item.variant.price) === null);
  const orderMessage = ["Hola DianubyHome, quiero consultar y confirmar disponibilidad para este pedido mayorista:", "", ...cartDetails.map((item) => { const price = numericPrice(item.variant.price); const subtotal = price ? ` — ${formatPrice(price * item.quantity)}` : " — Precio a consultar"; return `• ${item.quantity} × ${item.product.name} (${item.variant.label})${subtotal}`; }), "", `Total de unidades: ${totalUnits}`, `Total estimado: ${formatPrice(totalPrice)}${hasPriceToConfirm ? " + productos a consultar" : ""}`, "", "¿Me confirman disponibilidad, plazo y forma de pago?"].join("\n");

  function addToCart(product: Product, variantIndex: number, quantity = 1) { setCart((current) => { const existing = current.findIndex((item) => item.productId === product.id && item.variantIndex === variantIndex); if (existing === -1) return [...current, { productId: product.id, variantIndex, quantity }]; return current.map((item, index) => index === existing ? { ...item, quantity: item.quantity + quantity } : item); }); setSelected(null); setCartOpen(true); }
  function changeQuantity(productId: string, variantIndex: number, change: number) { setCart((current) => current.flatMap((item) => { if (item.productId !== productId || item.variantIndex !== variantIndex) return [item]; const quantity = item.quantity + change; return quantity > 0 ? [{ ...item, quantity }] : []; })); }
  function removeFromCart(productId: string, variantIndex: number) { setCart((current) => current.filter((item) => item.productId !== productId || item.variantIndex !== variantIndex)); }
  function openProduct(product: Product) { const firstImageIndex = variantImageIndex(product, 0); const preload = new Image(); preload.src = product.images[firstImageIndex].large; setSelectedVariant(0); setImageIndex(firstImageIndex); setModalQuantity(1); setSelected(product); }
  function selectVariant(product: Product, variantIndex: number) { setSelectedVariant(variantIndex); setImageIndex(variantImageIndex(product, variantIndex)); }

  return <main>
    <header className="topbar"><a className="wordmark" href="#inicio" aria-label="DianubyHome, inicio"><BrandLockup /></a><nav aria-label="Navegación principal"><a href="#coleccion">Colección</a><a href="#condiciones">Cómo comprar</a></nav><button className="header-cta cart-trigger" onClick={() => setCartOpen(true)}>Pedido <span className="cart-count">{totalUnits}</span></button></header>
    <section className="hero" id="inicio"><div className="hero-copy"><p className="kicker">CATÁLOGO MAYORISTA · 2026</p><h1>Espejos que<br /><em>transforman</em><br />ambientes.</h1><p className="hero-lead">Diseño, luz y tecnología fabricados en Argentina para potenciar tu negocio.</p><a className="primary-btn" href="#coleccion">Explorar colección <span aria-hidden="true">↓</span></a></div><div className="hero-media"><img src={PRODUCTS.find((product) => product.id === "capsula")?.images[0].large} alt="Espejo Cápsula de DianubyHome en un baño cálido" width="1500" height="1500" loading="eager" fetchPriority="high" /><div className="hero-note"><strong>Fabricación propia</strong><span>Terminaciones cuidadas, tecnología integrada.</span></div></div><div className="hero-index" aria-hidden="true">01—09</div></section>
    <section className="proof" aria-label="Condiciones destacadas"><div><strong>15</strong><span>unidades mínimas<br />combinables</span></div><div><strong>7 días</strong><span>de fabricación<br />estimada</span></div><div><strong>3 tonos</strong><span>en modelos<br />compatibles</span></div><div><strong>Envío</strong><span>incluido en el<br />pedido mayorista</span></div></section>
    <section className="collection" id="coleccion"><div className="section-heading"><div><p className="kicker">NUESTRA COLECCIÓN</p><h2>Encontrá el modelo<br />para cada cliente.</h2></div><p>Nueve líneas, múltiples tecnologías y una misma calidad de terminación.</p></div><div className="filters" role="group" aria-label="Filtrar productos">{FILTERS.map((item) => <button key={item} className={filter === item ? "active" : ""} onClick={() => setFilter(item)}>{item}</button>)}</div><div className="product-grid">{filtered.map((product, index) => <article className="product-card" key={product.id}><button className="product-image" onClick={() => openProduct(product)} aria-label={`Ver detalles de ${product.name}`}><img src={product.images[0].thumb} alt={product.imageAlts[0]} width="760" height="760" loading="lazy" decoding="async" />{product.badge && <span className="badge">{product.badge}</span>}<span className="card-number">{String(index + 1).padStart(2, "0")}</span></button><div className="product-copy"><div className="product-meta"><span>{product.line}</span><span>{product.category}</span></div><h3>{product.name}</h3><p>{product.summary}</p><div className="product-bottom"><div><small>DESDE</small><strong>{product.variants[0].price}</strong></div><div className="card-actions"><button onClick={() => openProduct(product)}>Ver modelo</button><button className="add-card" onClick={() => product.variants.length === 1 ? addToCart(product, 0) : openProduct(product)}>{product.variants.length === 1 ? "Agregar +" : "Elegir opción"}</button></div></div></div></article>)}</div></section>
    <section className="technology"><div className="technology-photo"><img src={PRODUCTS.find((product) => product.id === "nova")?.images[1].large} alt="Funciones inteligentes del espejo Nova Smart" width="1500" height="1500" loading="lazy" decoding="async" /></div><div className="technology-copy"><p className="kicker">TECNOLOGÍA QUE SE SIENTE</p><h2>Más que un espejo.<br /><em>Una experiencia.</em></h2><p>Desde un touch simple hasta control por app, nuestros modelos permiten ofrecer una solución para cada presupuesto.</p><div className="tech-list"><div><span>01</span><strong>Touch + dimmer</strong><p>Tres tonos de luz y memoria de intensidad.</p></div><div><span>02</span><strong>Sensores</strong><p>Presencia o control gestual sin contacto.</p></div><div><span>03</span><strong>Smart</strong><p>Pantalla, audio, desempañador y conectividad.</p></div></div></div></section>
    <section className="conditions" id="condiciones"><div><p className="kicker">CONDICIONES MAYORISTAS</p><h2>Simple de pedir.<br />Listo para vender.</h2></div><div className="conditions-grid"><article><span>01</span><h3>Armá tu mix</h3><p>Compra mínima de 15 unidades. Podés combinar modelos, medidas y tecnologías.</p></article><article><span>02</span><h3>Confirmá tu pedido</h3><p>Pago por transferencia o efectivo. Para iniciar la fabricación se abona el 50% del pedido y el saldo restante al momento de la entrega. Precios publicados sin IVA; emitimos Factura A +21%.</p></article><article><span>03</span><h3>Recibilo</h3><p>Fabricación estimada en 7 días y envío incluido en el pedido mayorista.</p></article></div></section>
    <section className="closing"><p className="kicker">HAGAMOS NEGOCIOS</p><h2>Sumá diseño y tecnología<br />a tu próxima venta.</h2><button className="primary-btn light" onClick={() => setCartOpen(true)}>Ver mi pedido ({totalUnits}) <ArrowIcon /></button><p className="smallprint">Precios mayoristas expresados en pesos argentinos, sin IVA. Sujetos a actualización.</p></section>
    <footer><a className="wordmark inverted" href="#inicio"><BrandLockup footer /></a><p>Fabricación argentina de espejos con luz y tecnología.</p><a href={generalWhatsappUrl} target="_blank" rel="noreferrer">WhatsApp · +54 9 3863 536486</a></footer>
    <button className="floating-whatsapp floating-cart" onClick={() => setCartOpen(true)} aria-label={`Ver pedido, ${totalUnits} unidades`}><span className="cart-bag" aria-hidden="true">▢</span><span>Mi pedido</span><strong>{totalUnits}</strong></button>
    {selected && <div className="modal" role="dialog" aria-modal="true" aria-label={`Detalle de ${selected.name}`} onMouseDown={(e) => e.currentTarget === e.target && setSelected(null)}><div className="modal-panel"><button className="close" onClick={() => setSelected(null)} aria-label="Cerrar detalle">×</button><div className="modal-gallery"><img src={selected.images[imageIndex].large} alt={selected.imageAlts[imageIndex]} width="1500" height="1500" decoding="async" />{selected.images.length > 1 && <div className="gallery-controls"><button onClick={() => setImageIndex((imageIndex - 1 + selected.images.length) % selected.images.length)} aria-label="Imagen anterior">←</button><span>{imageIndex + 1} / {selected.images.length}</span><button onClick={() => setImageIndex((imageIndex + 1) % selected.images.length)} aria-label="Imagen siguiente">→</button></div>}</div><div className="modal-content"><p className="kicker">LÍNEA {selected.line.toUpperCase()}</p><h2>{selected.name}</h2><p className="modal-summary">{selected.summary}</p><ul>{selected.features.map((feature) => <li key={feature}>{feature}</li>)}</ul><p className="selector-label">ELEGÍ UNA OPCIÓN</p><div className="price-table">{selected.variants.map((variant, index) => <button className={selectedVariant === index ? "active" : ""} onClick={() => selectVariant(selected, index)} key={variant.label}><span>{variant.label}</span><strong>{variant.price}</strong><i aria-hidden="true" /></button>)}</div><div className="spec-table">{selected.specs.map(([key, value]) => <div key={key}><span>{key}</span><strong>{value}</strong></div>)}</div><div className="add-row"><div className="quantity-control" aria-label="Cantidad"><button onClick={() => setModalQuantity((value) => Math.max(1, value - 1))} aria-label="Restar una unidad">−</button><span><small>CANTIDAD</small>{modalQuantity}</span><button onClick={() => setModalQuantity((value) => value + 1)} aria-label="Sumar una unidad">+</button></div><button className="primary-btn add-order" onClick={() => addToCart(selected, selectedVariant, modalQuantity)}>Agregar al pedido +</button></div><p className="modal-note">Compra mínima: 15 unidades combinables · Precios sin IVA</p></div></div></div>}
    {cartOpen && <div className="cart-overlay" role="dialog" aria-modal="true" aria-label="Mi pedido" onMouseDown={(event) => event.currentTarget === event.target && setCartOpen(false)}><aside className="cart-drawer"><div className="cart-header"><div><p className="kicker">PEDIDO MAYORISTA</p><h2>Mi selección</h2></div><button className="close cart-close" onClick={() => setCartOpen(false)} aria-label="Cerrar pedido">×</button></div>{cartDetails.length === 0 ? <div className="empty-cart"><span>0</span><h3>Tu pedido está vacío</h3><p>Elegí modelos y cantidades. El pedido se enviará completo por WhatsApp.</p><button className="primary-btn" onClick={() => setCartOpen(false)}>Explorar colección</button></div> : <><div className="cart-items">{cartDetails.map((item) => { const unitPrice = numericPrice(item.variant.price); const itemImageIndex = variantImageIndex(item.product, item.variantIndex); return <article className="cart-item" key={`${item.productId}-${item.variantIndex}`}><img src={item.product.images[itemImageIndex].thumb} alt={item.product.imageAlts[itemImageIndex]} width="760" height="760" loading="lazy" decoding="async" /><div className="cart-item-copy"><p>{item.product.line}</p><h3>{item.product.name}</h3><span>{item.variant.label}</span><strong>{unitPrice ? formatPrice(unitPrice * item.quantity) : "Consultar"}</strong><div className="cart-item-actions"><div className="quantity-control compact"><button onClick={() => changeQuantity(item.productId, item.variantIndex, -1)} aria-label="Restar unidad">−</button><span>{item.quantity}</span><button onClick={() => changeQuantity(item.productId, item.variantIndex, 1)} aria-label="Sumar unidad">+</button></div><button className="remove-item" onClick={() => removeFromCart(item.productId, item.variantIndex)}>Quitar</button></div></div></article>; })}</div><div className="cart-summary"><div><span>Unidades</span><strong>{totalUnits}</strong></div><div className="cart-total"><span>Total estimado</span><strong>{formatPrice(totalPrice)}</strong></div>{hasPriceToConfirm && <p>* Hay productos cuyo precio debe confirmarse.</p>}{totalUnits < 15 && <p className="minimum-warning">Faltan {15 - totalUnits} unidades para alcanzar el mínimo mayorista.</p>}<a className="primary-btn full whatsapp-order" href={whatsappUrl(orderMessage)} target="_blank" rel="noreferrer"><span className="whatsapp-dot" aria-hidden="true" /> Enviar pedido por WhatsApp <ArrowIcon /></a><button className="continue-shopping" onClick={() => setCartOpen(false)}>Seguir agregando productos</button></div></>}</aside></div>}
  </main>;
}
